name: "tests"

on:
  push:
    branches:
      - master
      - '*.x'

jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php-version: [ "8.2"]
        laravel: [11]
        
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        uses: php-actions/composer@v6
        
      - name: Start Centrifugo
        run: docker run -d -p 8000:8000 centrifugo/centrifugo:latest centrifugo --api_insecure

      - name: Check container status
        run: docker ps

      - name: Wait for server to be ready
        run: |
          while ! curl -s http://localhost:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 1
          done
        shell: bash
           
      - name: PHPUnit Tests
        run: vendor/bin/phpunit
